### ISSUE TITLE
Implement fallback attribute on cs:law-module

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero#95] opened 2020-10-19 02:35 UTC
Further to the point that arose in https://github.com/Juris-M/zotero/issues/93#issuecomment-711444901, I've implemented a "fallback" attribute on ``cs:law-module``.

When selecting a jurisdiction module for a legal item, the processor chooses the first module that matches the jurisdiction or one of its "ancestors" and either (a) has no value set for ``cs:law-module/@types`` or (b) lists the target item type in ``cs:law-module/@types``. When no match is found, the processor normally falls back to the ``us`` jurisdiction, which provides macros for all legal item types. Unfortunately, US citation formatting is an outlier and will be inappropriate for most other jurisdictions.

The ``fallback`` attribute on ``cs:law-module`` takes a single jurisdiction as its argument. If the target item type is not included in ``cs:law-module/@types``, the processor will try the ``fallback`` jurisdiction before continuing to ancestors of the item jurisdiction, if any. (The fallback is a single attempt: ancestors and fallbacks of the ``fallback`` jurisdiction itself are not processed.)

Where a module adopts all macros of the ``fallback``, ``cs:law-module/@types`` can be set to "none".

**Comment by fbennett** [comment] 2020-10-19 02:58
This and your latest changes to DE abbrevs and the JM-IBFD style are up now in the latest Mac beta.

How are we looking for a release?

**Comment by georgd** [comment] 2020-10-19 05:31
Thank you! I just applied the update but the NL Hoge Raad is still printed `hoge09/03219` (court code + docket no.) in the citation.

Edit: I think that was intended to be fixed in the previous beta?

**Comment by fbennett** [comment] 2020-10-19 09:01
Yes, I missed a detail, and the written-yesterday test framework that covers automated abbrevs also had a bug that masked the error. Have identified the problems and run trials again to be sure it's fixed. Taking a short break now, will get a refresh of the beta out within an hour or so. Truly close now! (He said again.)

**Comment by fbennett** [comment] 2020-10-19 10:27
Should be better this time ... the refreshed beta is now up.

**Comment by georgd** [comment] 2020-10-19 11:46
The NL-issue is fixed :), something else appeared, though: https://github.com/Juris-M/zotero/issues/96

**Closed as completed** 2020-10-21 02:40 UTC
