### ISSUE TITLE
 CSL error in LibreOffice after upgrading from multilingual Zotero to Juris-M

### ISSUE THREAD

**Issue by elbasi88** [Juris-M/zotero#22] opened 2016-06-30 07:35 UTC
Hello,

I recently upgraded from multilingual Zotero to Juris-M. However, there seems to be a problem with the LibreOffice plugin. I am using LibreOffice Version 4.3.3.2.

The problem doesn't occur when a create a new document and then insert citations, change preferences or update the whole document.

But when I open a document where I originally used multilingual Zotero, if I insert a new citation, want to change the preferences or update the whole document, it shows this error message:

"Zotero experienced an error updating your document.
CSL error: Level mismatch error: wanted bib_entry but found group"

I have tried many times and sometimes, LibreOffice also crashed completely.

I have no idea how to fix this and hope someone can help me with my problem.

Thanks in advance!

**Comment by fbennett** [comment] 2016-07-02 21:22
This should be fixed in the latest citeproc-js release. You can try it by installing one of the [Propachi plugins](https://juris-m.github.io/downloads/#csl-stuff) from the Juris-M site (you will want to remove the plugin when the next Juris-M upgrade comes out).

**Comment by fbennett** [comment] 2016-07-02 21:23
Closing as fixed.

**Closed as completed by fbennett** 2016-07-02 21:23 UTC

**Comment by elbasi88** [comment] 2016-07-03 08:04
It worked, thank you so much!

**Comment by fbennett** [comment] 2016-07-03 21:38
Good to hear! Could I ask what platform you are using (Mac, Windows, Linux), and the version?

I'm curious because the crash was caused by a difference in the logging function that caused the processor to fall back (intentionally) to a hard crash. The fix uses a "dumber" logging mechanism instead of forcing a crash; that's the right thing to do, but I've had one other report of this (from a lab in Germany), and I'm curious about the variance among platforms.

**Comment by elbasi88** [comment] 2016-07-03 22:57
I am using Linux, Gnome Version 3.14.1. Hope this helps!

**Comment by fbennett** [comment] 2016-07-03 23:12
Thanks. Curiouser and curiouser.
