### ISSUE TITLE
Cannot add languages

### ISSUE THREAD

**Issue by Langdi** [Juris-M/zotero#69] opened 2020-01-14 11:29 UTC
Hi,
I wanted to try Juris-M, but I'm already stuck on the first step - adding a language. When I go to Settings -> Languages and input a language the dropdown is either:
1) correctly shown
2) doesn't appear at all
3) appears, but only shows white entries.

In any case selecting an entry just resets the field, but does not add the language below. Is this a regression bug or is there something I'm missing?

Version: Jurism Zotero 5.0.80m9
OS: Linux 5.4.6-2-MANJARO with KDE Plasma 5.17

**Comment by fbennett** [comment] 2020-01-14 23:50
Thanks for reporting. I run Linux for my own work, and this was tested
before the release - but there is on iously a problem. I'll check this out
today and get back.

**Comment by fbennett** [comment] 2020-01-15 06:24
Thanks again for reporting this fault. I was able to reproduce it
immediately on my own Linux install of 5.0.80m9, so I must have just been
careless.

I've applied a fix, which is now up for Linux, as version 5.0.81m1. The
update should come through for you automatically within 24 hours, or you
can update immediately with Help -> Check for updates.

Let me know if you have any trouble with it.

Frank Bennett

**Comment by Langdi** [comment] 2020-01-15 07:47
Thanks for your help. Unfortunately, it does not fix things for me. The dropdown now works correctly, but selection of an entry still just clears the text field without any other (observable) effect.

**Comment by fbennett** [comment] 2020-01-15 07:59
Ha. Sorry about that, I'll push further.

**Comment by fbennett** [comment] 2020-01-16 06:31
This should be fixed properly in 5.0.81m2, now available for Linux, and coming soon for Windows and Mac. Apologies for the false start, and looking forward to hearing how you get on.

**Comment by Langdi** [comment] 2020-01-16 12:51
Thanks a lot, it works for me now!

However, contrary to what is shown in the tutorial the Juris-M columns are all greyed out:

![image](https://user-images.githubusercontent.com/2018510/72526546-f5ce9e80-3866-11ea-8b56-3b6677ae472d.png)

I am not sure what this does, everything seems to work.Thanks again.

**Comment by fbennett** [comment] 2020-01-16 13:11
Great, thanks for posting back. Both columns are grayed out on purpose at
the moment.

Originally, "screen" enabled showing a variant field values in the center
column, as a convenience for users that didn't read the original language
of sources. That depended on a large and complex customized database call
in the code of the client. Jurism needs to "chase" the code of its parent
project Zotero, and I stripped out that feature to save time and simplify
maintenance.

The "sort" feature sorts the center column using using specified variants
if available. It suffers from the same complexity problem, but it would be
good to bring back because some language (Chinese, Japanese) should
properly be sorted on a phonetic, not on the written text value - and so I
have left the columns in place. To avoid confusion, though, that pair of
columns should probably be hidden entirely until at least the sort feature
is hooked up again.

Frank

**Closed as completed** 2020-01-18 13:56 UTC
